-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggWHgZyztNsIgANV4
pCvhgRbJyuSLa645FQVfkS27gJugCgYIKoZIzj0DAQehRANCAAQd3lzHHIXjcyyA
ALEAeczMA27t8XMgZZ5i4fXtP3dRXHt4uGcxrtHBfnSGGSq6q7eo4wTqDy/SLpRk
GbXW4O3X
-----END PRIVATE KEY-----